// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TRC.Infrastructure.Persistence;

#nullable disable

namespace TRC.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260717145905_Phase4BookingOtp")]
    partial class Phase4BookingOtp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TRC.Domain.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeOnly?>("AssignedEnd")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("AssignedStart")
                        .HasColumnType("time without time zone");

                    b.Property<int>("BookingOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConsultationDayId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MeetingLink")
                        .HasColumnType("text");

                    b.Property<Guid>("PhoneProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConsultationDayId");

                    b.HasIndex("PhoneProfileId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("TRC.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasColumnType("jsonb");

                    b.Property<string>("EntityId")
                        .HasColumnType("text");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("TRC.Domain.Entities.BusinessPeriodData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PhoneProfileId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalPurchases")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalSales")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("VatDeclared")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "PhoneProfileId", "Year", "Month")
                        .IsUnique();

                    b.ToTable("BusinessPeriodData");
                });

            modelBuilder.Entity("TRC.Domain.Entities.Commodity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("BenchmarkPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HSCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HSCode")
                        .IsUnique();

                    b.ToTable("Commodities");
                });

            modelBuilder.Entity("TRC.Domain.Entities.ConsultationDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("BookingCutoff")
                        .HasColumnType("time without time zone");

                    b.Property<int>("BufferMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxBookings")
                        .HasColumnType("integer");

                    b.Property<int>("SessionMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TimesAssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeOnly>("WindowEnd")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("WindowStart")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("ConsultationDays");
                });

            modelBuilder.Entity("TRC.Domain.Entities.Import", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AssessableValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CfrValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Consignee")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HSCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("HasBillOfLading")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasCommercialInvoice")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasMushak")
                        .HasColumnType("boolean");

                    b.Property<decimal>("InvoiceValueUsd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherCosts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("HSCode");

                    b.HasIndex("UserId");

                    b.ToTable("Imports");
                });

            modelBuilder.Entity("TRC.Domain.Entities.NotificationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Channel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<int>("Language")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderMessageId")
                        .HasColumnType("text");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("NotificationLogs");
                });

            modelBuilder.Entity("TRC.Domain.Entities.OtpCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PhoneProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PhoneProfileId");

                    b.ToTable("OtpCodes");
                });

            modelBuilder.Entity("TRC.Domain.Entities.PhoneProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("BlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MissedCount")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("PreferredLanguage")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("PhoneProfiles");
                });

            modelBuilder.Entity("TRC.Domain.Entities.QuickCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BoeValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PaymentValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("PhoneProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("RiskBand")
                        .HasColumnType("integer");

                    b.Property<decimal>("VariancePct")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PhoneProfileId");

                    b.ToTable("QuickChecks");
                });

            modelBuilder.Entity("TRC.Domain.Entities.RiskAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AssessedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ImportId")
                        .HasColumnType("uuid");

                    b.Property<string>("NotEvaluable")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("integer");

                    b.Property<int>("RiskScore")
                        .HasColumnType("integer");

                    b.Property<string>("TriggeredRules")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ImportId");

                    b.ToTable("RiskAssessments");
                });

            modelBuilder.Entity("TRC.Domain.Entities.RiskRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastReviewed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PhaseTag")
                        .HasColumnType("integer");

                    b.Property<string>("Rationale")
                        .HasColumnType("text");

                    b.Property<string>("ThresholdJson")
                        .HasColumnType("text");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("RiskRules");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Code = "R1",
                            CreatedAt = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            LastReviewed = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Declared VAT > 10% below computed VAT",
                            PhaseTag = 1,
                            Rationale = "Approved default (TRC-RSK-002 Rev 1.1).",
                            Weight = 15
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Code = "R2",
                            CreatedAt = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            LastReviewed = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Return vs financial statements differ > 15%",
                            PhaseTag = 2,
                            Rationale = "Approved default (TRC-RSK-002 Rev 1.1).",
                            Weight = 20
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Code = "R3",
                            CreatedAt = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            LastReviewed = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Supplier on watchlist",
                            PhaseTag = 2,
                            Rationale = "Approved default (TRC-RSK-002 Rev 1.1).",
                            Weight = 25
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Code = "R4",
                            CreatedAt = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            LastReviewed = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Unit value < 90% of commodity benchmark",
                            PhaseTag = 2,
                            Rationale = "Approved default (TRC-RSK-002 Rev 1.1).",
                            Weight = 20
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Code = "R5",
                            CreatedAt = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            LastReviewed = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "AV deviates > 50% from 12-month rolling average",
                            PhaseTag = 1,
                            Rationale = "Approved default (TRC-RSK-002 Rev 1.1).",
                            Weight = 15
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Code = "R6",
                            CreatedAt = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            LastReviewed = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sales below purchases by > 20%",
                            PhaseTag = 2,
                            Rationale = "Approved default (TRC-RSK-002 Rev 1.1).",
                            Weight = 10
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Code = "R7",
                            CreatedAt = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            LastReviewed = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "HS code inconsistent with description/history",
                            PhaseTag = 1,
                            Rationale = "Approved default (TRC-RSK-002 Rev 1.1).",
                            Weight = 15
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Code = "R8",
                            CreatedAt = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            LastReviewed = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = ">=3 of last 6 declarations below benchmark",
                            PhaseTag = 2,
                            Rationale = "Approved default (TRC-RSK-002 Rev 1.1).",
                            Weight = 20
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Code = "R9",
                            CreatedAt = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            LastReviewed = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Large turnover, no audit in 3 years",
                            PhaseTag = 2,
                            Rationale = "Approved default (TRC-RSK-002 Rev 1.1).",
                            Weight = 10
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Code = "R10",
                            CreatedAt = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            LastReviewed = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Round-number / repeated invoice patterns",
                            PhaseTag = 1,
                            Rationale = "Approved default (TRC-RSK-002 Rev 1.1).",
                            Weight = 8
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            Code = "R11",
                            CreatedAt = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            LastReviewed = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Required document missing/inconsistent",
                            PhaseTag = 1,
                            Rationale = "Approved default (TRC-RSK-002 Rev 1.1).",
                            Weight = 12
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            Code = "R12",
                            CreatedAt = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            LastReviewed = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "External intelligence hit",
                            PhaseTag = 2,
                            Rationale = "Approved default (TRC-RSK-002 Rev 1.1).",
                            Weight = 30
                        });
                });

            modelBuilder.Entity("TRC.Domain.Entities.TaxBreakdown", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BaseAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ImportId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TaxType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ImportId");

                    b.ToTable("TaxBreakdowns");
                });

            modelBuilder.Entity("TRC.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PreferredLanguage")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshTokenHash")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TRC.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("TRC.Domain.Entities.ConsultationDay", "ConsultationDay")
                        .WithMany("Appointments")
                        .HasForeignKey("ConsultationDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TRC.Domain.Entities.PhoneProfile", "PhoneProfile")
                        .WithMany("Appointments")
                        .HasForeignKey("PhoneProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsultationDay");

                    b.Navigation("PhoneProfile");
                });

            modelBuilder.Entity("TRC.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("TRC.Domain.Entities.User", null)
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("TRC.Domain.Entities.Import", b =>
                {
                    b.HasOne("TRC.Domain.Entities.User", "User")
                        .WithMany("Imports")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TRC.Domain.Entities.OtpCode", b =>
                {
                    b.HasOne("TRC.Domain.Entities.PhoneProfile", "PhoneProfile")
                        .WithMany("OtpCodes")
                        .HasForeignKey("PhoneProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhoneProfile");
                });

            modelBuilder.Entity("TRC.Domain.Entities.QuickCheck", b =>
                {
                    b.HasOne("TRC.Domain.Entities.PhoneProfile", "PhoneProfile")
                        .WithMany("QuickChecks")
                        .HasForeignKey("PhoneProfileId");

                    b.Navigation("PhoneProfile");
                });

            modelBuilder.Entity("TRC.Domain.Entities.RiskAssessment", b =>
                {
                    b.HasOne("TRC.Domain.Entities.Import", "Import")
                        .WithMany("RiskAssessments")
                        .HasForeignKey("ImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Import");
                });

            modelBuilder.Entity("TRC.Domain.Entities.TaxBreakdown", b =>
                {
                    b.HasOne("TRC.Domain.Entities.Import", "Import")
                        .WithMany("TaxBreakdowns")
                        .HasForeignKey("ImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Import");
                });

            modelBuilder.Entity("TRC.Domain.Entities.ConsultationDay", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("TRC.Domain.Entities.Import", b =>
                {
                    b.Navigation("RiskAssessments");

                    b.Navigation("TaxBreakdowns");
                });

            modelBuilder.Entity("TRC.Domain.Entities.PhoneProfile", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("OtpCodes");

                    b.Navigation("QuickChecks");
                });

            modelBuilder.Entity("TRC.Domain.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Imports");
                });
#pragma warning restore 612, 618
        }
    }
}
